[package]
name = "midnight"
version = "0.1.0"
authors = ["alex"]

[dependencies]
piston = "0.17.0"
sdl2 = "0.13.0"
pistoncore-sdl2_window = "0.23.0"
fps_counter = "0.2.0"
piston2d-opengl_graphics = "0.23.0"
piston2d-graphics = "0.13.1"
piston2d-sprite = "0.20.0"
find_folder = "0.3.0"
